import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

let students = [], supabaseClient, session, signingUp = false, realtimeChannel;
const $ = (s) => document.querySelector(s);
const safe = (v) => String(v).replace(/[&<>"']/g, (m) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[m]));
const fromRow = (r) => ({ key: r.id, name: r.full_name, id: r.student_id, email: r.email, course: r.course, attendance: r.attendance, grade: r.grade });
function toast(message) { const target = $('#toast'); target.textContent = message; target.classList.add('show'); setTimeout(() => target.classList.remove('show'), 2600); }
async function request(path, options = {}) { const response = await fetch(path, { ...options, headers: { 'Content-Type': 'application/json', ...(session ? { Authorization: `Bearer ${session.access_token}` } : {}), ...options.headers } }); if (response.status === 204) return null; const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Request failed.'); return body; }
function render() { const query = $('#search').value.toLowerCase(), course = $('#courseFilter').value; const shown = students.filter((s) => (!course || s.course === course) && Object.values(s).join(' ').toLowerCase().includes(query)); $('#studentRows').innerHTML = shown.map((s) => `<tr><td><div class="student-name">${safe(s.name)}</div><div class="student-email">${safe(s.email)}</div></td><td>${safe(s.id)}</td><td>${safe(s.course)}</td><td><span class="pill ${s.attendance >= 85 ? 'good' : 'warn'}">${s.attendance}%</span></td><td class="grade">${s.grade}%</td><td class="row-actions"><button data-edit="${s.key}">✎</button><button data-delete="${s.key}">×</button></td></tr>`).join(''); $('#emptyState').hidden = shown.length > 0; $('#totalStudents').textContent = students.length; const average = (key) => students.length ? Math.round(students.reduce((sum, s) => sum + s[key], 0) / students.length) : 0; $('#avgAttendance').textContent = `${average('attendance')}%`; $('#avgGrade').textContent = `${average('grade')}%`; $('#attendanceList').innerHTML = students.map((s) => `<div class="attendance-item"><b>${safe(s.name)}</b><label><input type="checkbox" data-key="${s.key}" ${s.attendance >= 80 ? 'checked' : ''}> Present</label></div>`).join(''); $('#gradeList').innerHTML = students.map((s) => `<div class="grade-item"><b>${safe(s.name)}</b><div class="grade-bar"><span style="width:${s.grade}%"></span></div><strong>${s.grade}%</strong></div>`).join(''); $('#courseFilter').innerHTML = '<option value="">All courses</option>' + [...new Set(students.map((s) => s.course))].map((v) => `<option ${course === v ? 'selected' : ''}>${safe(v)}</option>`).join(''); }
async function loadStudents() { try { students = (await request('/api/students')).map(fromRow); render(); } catch (error) { toast(error.message); } }
function openStudent(student) { $('#studentForm').reset(); $('#studentKey').value = student?.key || ''; $('#modalTitle').textContent = student ? 'Edit student' : 'Add student'; ['name', 'id', 'email', 'course', 'attendance', 'grade'].forEach((key) => { if (student) $(key === 'id' ? '#studentId' : `#${key}`).value = student[key]; }); $('#studentModal').showModal(); }
function setAuthMode() { $('#authTitle').textContent = signingUp ? 'Create account' : 'Sign in'; $('#authSubmit').textContent = signingUp ? 'Create account' : 'Sign in'; $('#toggleAuth').textContent = signingUp ? 'I already have an account' : 'Create account'; $('#authFields').classList.toggle('signup', signingUp); $('#authName').required = signingUp; }
async function syncSession(nextSession) { session = nextSession; $('#sessionButton').textContent = session ? 'Sign out' : 'Sign in'; if (!session) { students = []; render(); return; } try { const me = await request('/api/me'); $('.sidebar-footer b').textContent = me.full_name || me.email; $('.sidebar-footer small').textContent = me.role; await loadStudents(); if (realtimeChannel) supabaseClient.removeChannel(realtimeChannel); realtimeChannel = supabaseClient.channel('campusflow-live').on('postgres_changes', { event: '*', schema: 'public', table: 'students' }, loadStudents).subscribe(); } catch (error) { toast(error.message); } }

$('#sessionButton').onclick = async () => { if (!session) return $('#authModal').showModal(); await supabaseClient.auth.signOut(); };
$('#closeAuth').onclick = () => $('#authModal').close(); $('#toggleAuth').onclick = () => { signingUp = !signingUp; setAuthMode(); };
$('#authForm').onsubmit = async (event) => { event.preventDefault(); if (!supabaseClient) return toast('Supabase setup is required first.'); const email = $('#authEmail').value.trim(), password = $('#authPassword').value; const result = signingUp ? await supabaseClient.auth.signUp({ email, password, options: { data: { full_name: $('#authName').value.trim() } } }) : await supabaseClient.auth.signInWithPassword({ email, password }); if (result.error) return toast(result.error.message); $('#authModal').close(); if (signingUp && !result.data.session) toast('Check your email to confirm the account, then sign in.'); };
$('#addStudent').onclick = $('#heroAdd').onclick = () => openStudent(); $('#closeModal').onclick = $('#cancelModal').onclick = () => $('#studentModal').close(); $('#search').oninput = render; $('#courseFilter').onchange = render;
$('#studentRows').onclick = async (event) => { const id = event.target.dataset.edit || event.target.dataset.delete; if (!id) return; const student = students.find((item) => item.key === id); if (event.target.dataset.edit) return openStudent(student); if (!confirm(`Remove ${student.name}?`)) return; try { await request(`/api/students/${id}`, { method: 'DELETE' }); await loadStudents(); } catch (error) { toast(error.message); } };
$('#studentForm').onsubmit = async (event) => { event.preventDefault(); const id = $('#studentKey').value, payload = { studentId: $('#studentId').value.trim(), name: $('#name').value.trim(), email: $('#email').value.trim(), course: $('#course').value.trim(), attendance: Number($('#attendance').value), grade: Number($('#grade').value) }; try { await request(id ? `/api/students/${id}` : '/api/students', { method: id ? 'PATCH' : 'POST', body: JSON.stringify(payload) }); $('#studentModal').close(); await loadStudents(); toast('Student saved.'); } catch (error) { toast(error.message); } };
$('#saveAttendance').onclick = async () => { try { await Promise.all([...document.querySelectorAll('#attendanceList input')].map((input) => request('/api/attendance', { method: 'POST', body: JSON.stringify({ studentId: input.dataset.key, date: new Date().toISOString().slice(0, 10), status: input.checked ? 'present' : 'absent' }) }))); toast('Today’s attendance saved.'); } catch (error) { toast(error.message); } };
$('#exportBtn').onclick = () => { const csv = ['Name,Student ID,Email,Course,Attendance,Grade', ...students.map((s) => [s.name, s.id, s.email, s.course, s.attendance, s.grade].map((v) => `"${String(v).replaceAll('"', '""')}"`).join(','))].join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = 'students.csv'; link.click(); URL.revokeObjectURL(link.href); };

async function bootstrap() { const config = await request('/api/config'); if (!config.configured || !config.supabaseAnonKey) return toast('Add the Supabase values to .env, then restart the server.'); supabaseClient = createClient(config.supabaseUrl, config.supabaseAnonKey); const { data } = await supabaseClient.auth.getSession(); await syncSession(data.session); supabaseClient.auth.onAuthStateChange((_event, nextSession) => syncSession(nextSession)); }
setAuthMode(); render(); bootstrap().catch((error) => toast(error.message));
